# ESP8266 ESP-01 1M
[env]
framework = arduino
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    plerup/EspSoftwareSerial @ ^8.2.0
    bmellink/IBusBM @ ^1.1.4

[gps_config]
current_gps = ublox
#current_gps = quectel

[common]
base_flags = 
            -DGPS_${gps_config.current_gps}

# ESP8266 ESP-01 1Mega
[env:esp01_1m]
platform = espressif8266
board = esp01_1m
build_flags = ${common.base_flags}
            -DGPS_RX_PIN=0
            -DGPS_TX_PIN=2
            -DPIN_FACTORY_RESET=2
            -DPIN_LED=1
            -DFEATURE_OTA
            -DFEATURE_RECEIVER
            -DFEATURE_STATISTICS

# ESP8266 ESP-01 512k
[env:esp01_512k]
platform = espressif8266
board = esp01
build_flags = ${common.base_flags}
            -DGPS_RX_PIN=0
            -DGPS_TX_PIN=2
            -DPIN_FACTORY_RESET=2
            -DPIN_LED=1
            -DFEATURE_OTA
            -DFEATURE_RECEIVER
            -DFEATURE_STATISTICS

# ESP32 DEVKIT (NODEMCU)
[env:esp32_kit]
platform = espressif32
board = esp32dev

monitor_speed = 115200
upload_speed = 921600
build_flags = ${common.base_flags}
    -DiBus_RX=16
    -DiBus_TX=17
    -DGPS_RX_PIN=4
    -DGPS_TX_PIN=2
    -DFEATURE_OTA
    -DFEATURE_RECEIVER
    -DFEATURE_STATISTICS
    -DFEATURE_IBUS
 
 # ESP32C3 DEVKIT
[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1

monitor_speed = 115200
upload_speed = 921600
build_flags = ${common.base_flags}
    -DiBus_RX=20
    -DiBus_TX=21
    -DGPS_RX_PIN=8
    -DGPS_TX_PIN=9
    -DPIN_FACTORY_RESET=2
    -DPIN_LED=3
    -DCONFIG_IDF_TARGET_ESP32C3
    -DFEATURE_OTA
    -DFEATURE_RECEIVER
    -DFEATURE_STATISTICS
    -DFEATURE_IBUS