# ESP8266 ESP-01 1M
[env]
framework = arduino
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    bmellink/IBusBM @ ^1.1.4

[env:software_serial_config]
extends = env
lib_deps =
    ${env.lib_deps}
    plerup/EspSoftwareSerial @ ^8.2.0

[gps_config]
# Select the GPS module you are using by uncommenting the corresponding line.
# Only one GPS module should be selected at a time.
current_gps = ublox
#current_gps = quectel

[options]
# Comment the features you don't want to enable. By default, all features are enabled.
features_esp32 = 
    -DFEATURE_OTA
    -DFEATURE_RECEIVER
    -DFEATURE_STATISTICS
    -DFEATURE_IBUS

features_esp8266 = 
    -DFEATURE_OTA
    -DFEATURE_RECEIVER
    -DFEATURE_STATISTICS

# ESP8266 ESP-01 1Mega
[env:esp01_1m]
extends = env:software_serial_config
platform = espressif8266
board = esp01_1m
build_flags = ${options.features_esp8266}
        -DGPS_${gps_config.current_gps}
        -DGPS_RX_PIN=0
        -DGPS_TX_PIN=2
        -DPIN_FACTORY_RESET=2
        -DPIN_LED=1

# ESP8266 ESP-01 512k
[env:esp01_512k]
extends = env:software_serial_config
platform = espressif8266
board = esp01
build_flags = ${options.features_esp8266}
    -DGPS_${gps_config.current_gps}
    -DGPS_RX_PIN=0
    -DGPS_TX_PIN=2
    -DPIN_FACTORY_RESET=2
    -DPIN_LED=1

# ESP32 DEVKIT (NODEMCU)
[env:esp32_devKitC]
platform = espressif32
board = esp32dev

monitor_speed = 115200
upload_speed = 921600
build_flags = ${options.features_esp32}
    -DGPS_${gps_config.current_gps}
    -DiBus_RX=16
    -DiBus_TX=17
    -DGPS_RX_PIN=4
    -DGPS_TX_PIN=2
 
 # ESP32C3 DEVKIT
[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1

monitor_speed = 115200
upload_speed = 921600
build_flags = ${options.features_esp32}
    -DGPS_${gps_config.current_gps}
    -DiBus_RX=20
    -DiBus_TX=21
    -DGPS_RX_PIN=8
    -DGPS_TX_PIN=9
    -DPIN_FACTORY_RESET=2
    -DPIN_LED=3
