[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    plerup/EspSoftwareSerial @ ^8.2.0
    bmellink/IBusBM @ ^1.1.4

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    plerup/EspSoftwareSerial @ ^8.2.0
    bmellink/IBusBM @ ^1.1.4